// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm_rHwa4Mg26KuhwVE7Be9MqDWxPpWw9w',
    appId: '1:389150416948:web:8ba233c57ac1554efcaa61',
    messagingSenderId: '389150416948',
    projectId: 'chatapp-f862d',
    authDomain: 'chatapp-f862d.firebaseapp.com',
    storageBucket: 'chatapp-f862d.firebasestorage.app',
    measurementId: 'G-KYE61HZYTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPU5R0BtCDxYoh7j8wcjZo9a6r3dC6zrI',
    appId: '1:389150416948:android:71b680163790c2fdfcaa61',
    messagingSenderId: '389150416948',
    projectId: 'chatapp-f862d',
    storageBucket: 'chatapp-f862d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgbMJHFeot9iYKrT1k4H7slIyHyKHce40',
    appId: '1:389150416948:ios:91eeba7b7805dd4afcaa61',
    messagingSenderId: '389150416948',
    projectId: 'chatapp-f862d',
    storageBucket: 'chatapp-f862d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
